model_list:
  - model_name: mistral-small-latest
    litellm_params:
      model: mistral/mistral-small-latest
      api_key: os.environ/MISTRAL_API_KEY

  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY

router_settings:
  fallbacks: [{"mistral-small-latest": ["claude-3-haiku-20240307"]}]

general_settings: 
  master_key: "os.environ/PROXY_API_KEY" # You create this password